let json = 
    {
        apiVersion: '2.0.0.1',
        agentId: '310000015002365829',
        opTellerId: 'chengfayun2020',
        tellerId: 'admin',
        reqSerialNum: '12321434',
        isSendMes: '1',
        merchClass: '1',
        merchName: '乘法云',
        // provId: '北京',
        // cityId: '北京市',
        // areaId: '朝阳区',
        // businessShours: '09:00-18:00',
        // businessEhours: '',
        // contactName: '2342354',
        // contactIdType: '1',
        // contactIdNo: '42900419931144',
        // contactIdValidType: '1',
        // contactIdSdate: '20200602',
        // contactIdEdate: '20200602',
        // contactTelno: '13164602219',
        // contactEmail: 'smile@3214.com',
        // csTel: '324234234',
        // merchAddr: '3453453',
        // isCreditCode: '2',
        // creditCode: '',
        // regCode: 'sdfsdf ',
        // licType: '',
        // licSdate: '20200603',
        // licEdate: '20200602',
        // orgCode: '',
        // idValidType: '2',
        // idSdate: '20200602',
        // idEdate: '20200602',
        // accountIdType: '1',
        // accountIdNo: 'dfgdfg',
        // accountIdValidType: '1',
        // accountIdSdate: '20200602',
        // accountIdEdate: '20200602',
        // legalName: '乘法云',
        // idType: '1',
        // idNo: '234234354353',
        // isPrivate: '1',
        // bankActName: 'fdgdfg ',
        // bankActId: 'ewrwe',
        // bankProvId: '浙江',
        // bankCityId: '杭州市',
        // bankName: '工商银行',
        // bankUnionCode: '',
        // subBankName: '',
        // settleTerm: '',
        // fee01: '',
        // settleBusiness: '',
        // fee28: '',
        // fee01MerId: '',
        // settleRemark: '',
        // pnrpayMertype: '2'
      }

for (let item in json) {
    json[item] = encodeURIComponent(json[item])
}
console.log((JSON.stringify(json)));

console.log(decodeURI(JSON.stringify(json)));